// Sample data for guest/demo mode. All dates are computed relative to today
// so the demo always looks current. This data never touches localStorage or GitHub.

import { todayISO } from './dates.js';

// Two random display names picked fresh each time the module is imported,
// so every demo session shows different names instead of the real ones.
const NAME_POOL = ['Alex', 'Jordan', 'Sam', 'Casey', 'Riley', 'Morgan', 'Drew', 'Quinn'];
function pickTwo() {
  const pool = [...NAME_POOL];
  const i1 = Math.floor(Math.random() * pool.length);
  const [n1] = pool.splice(i1, 1);
  const n2 = pool[Math.floor(Math.random() * pool.length)];
  return [n1, n2];
}
export const DEMO_WHO_NAMES = pickTwo(); // [person1, person2]

function addDays(iso, n) {
  const d = new Date(iso + 'T00:00:00');
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export function getDemoData() {
  const today = todayISO();
  const thisMonth = today.slice(0, 7);
  const thisYear = today.slice(0, 4);

  return {
    updated_at: today + 'T00:00:00.000Z',

    settings: {
      paycheck: {
        who: 'chang',
        amount: 4200,
        frequency: 'biweekly',
        next_date: addDays(today, 5),
      },
    },

    bills: [
      {
        id: 'demo-bill-1',
        brand: 'Landlord',
        name: 'Rent',
        type: 'other',
        amount: 2800,
        frequency: 'monthly',
        day: 1,
        who: 'joint',
        variable: false,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-bill-2',
        brand: 'ConEd',
        name: 'Electric',
        type: 'utility',
        amount: null,
        frequency: 'monthly',
        day: 15,
        who: 'joint',
        variable: true,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-bill-3',
        brand: 'Chase',
        name: 'Sapphire Reserve',
        type: 'cc',
        amount: 550,
        frequency: 'annual',
        day: 20,
        who: 'chang',
        cc: { last_used: addDays(today, -8) },
        variable: false,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-bill-4',
        brand: 'Amex',
        name: 'Gold Card',
        type: 'cc',
        amount: 250,
        frequency: 'annual',
        day: 8,
        who: 'kiju',
        cc: {
          last_used: addDays(today, -55),
          apr_zero: { expires_date: addDays(today, 45), months_left: 2, balance_remaining: 1800 },
        },
        variable: false,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-bill-5',
        brand: 'Spectrum',
        name: 'Internet',
        type: 'utility',
        amount: 79.99,
        frequency: 'monthly',
        day: 22,
        who: 'joint',
        variable: false,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-bill-6',
        brand: 'Mom',
        name: 'Cash transfer',
        type: 'gift',
        amount: 500,
        frequency: 'monthly',
        day: 5,
        who: 'chang',
        variable: false,
        archived: false,
        notes: 'Monthly support',
      },
    ],

    payments: [
      {
        id: 'demo-pay-1',
        bill_id: 'demo-bill-1',
        period: thisMonth,
        status: 'paid',
        pending_amount: 2800,
        paid_amount: 2800,
        paid_date: addDays(today, -4),
        scheduled_date: null,
        marker: '',
        notes: '',
      },
      {
        id: 'demo-pay-2',
        bill_id: 'demo-bill-5',
        period: thisMonth,
        status: 'scheduled',
        pending_amount: 79.99,
        paid_amount: null,
        paid_date: null,
        scheduled_date: addDays(today, 16),
        marker: '',
        notes: '',
      },
      {
        id: 'demo-pay-3',
        bill_id: 'demo-bill-6',
        period: thisMonth,
        status: 'needs_confirm',
        pending_amount: 500,
        paid_amount: null,
        paid_date: null,
        scheduled_date: addDays(today, -1),
        marker: '',
        notes: '',
      },
    ],

    subscriptions: [
      {
        id: 'demo-sub-1',
        name: 'Netflix',
        amount: 22.99,
        frequency: 'monthly',
        status: 'active',
        next_renewal: addDays(today, 12),
        billed_to: 'Chase Sapphire Reserve',
        subsidized_amount: null,
        trial_ends: null,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-sub-2',
        name: 'Spotify Family',
        amount: 16.99,
        frequency: 'monthly',
        status: 'active',
        next_renewal: addDays(today, 3),
        billed_to: 'Amex Gold',
        subsidized_amount: null,
        trial_ends: null,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-sub-3',
        name: 'iCloud 2TB',
        amount: 9.99,
        frequency: 'monthly',
        status: 'active',
        next_renewal: addDays(today, 19),
        billed_to: 'Apple Card',
        subsidized_amount: null,
        trial_ends: null,
        archived: false,
        notes: '',
      },
      {
        id: 'demo-sub-4',
        name: 'Adobe Creative Cloud',
        amount: 599.88,
        frequency: 'annual',
        status: 'non_renewing',
        next_renewal: addDays(today, 21),
        billed_to: 'Chase Sapphire Reserve',
        subsidized_amount: null,
        trial_ends: null,
        archived: false,
        notes: 'Auto-renew turned off — access until end date',
      },
      {
        id: 'demo-sub-5',
        name: 'Gym Membership',
        amount: 49,
        frequency: 'monthly',
        status: 'active',
        next_renewal: addDays(today, 6),
        billed_to: null,
        subsidized_amount: null,
        trial_ends: addDays(today, 6),
        archived: false,
        notes: 'Trial converting soon',
      },
    ],

    perks: [
      {
        id: 'demo-perk-1',
        card: 'Chase Sapphire Reserve',
        name: 'Travel Credit',
        value: 300,
        frequency: 'annual',
        reset_day: 1,
        who: 'chang',
        archived: false,
        notes: '',
      },
      {
        id: 'demo-perk-2',
        card: 'Chase Sapphire Reserve',
        name: 'DoorDash DashPass',
        value: 60,
        frequency: 'annual',
        reset_day: 1,
        who: 'chang',
        archived: false,
        notes: '',
      },
      {
        id: 'demo-perk-3',
        card: 'Amex Gold',
        name: 'Dining Credit',
        value: 10,
        frequency: 'monthly',
        reset_day: 1,
        who: 'kiju',
        archived: false,
        notes: '',
      },
      {
        id: 'demo-perk-4',
        card: 'Amex Gold',
        name: 'Uber Cash',
        value: 10,
        frequency: 'monthly',
        reset_day: 1,
        who: 'kiju',
        archived: false,
        notes: '',
      },
    ],

    perk_claims: [
      {
        id: 'demo-claim-1',
        perk_id: 'demo-perk-1',
        period: thisYear,
        status: 'claimed',
        claimed_date: addDays(today, -30),
        notes: 'Used for flights',
      },
      {
        id: 'demo-claim-2',
        perk_id: 'demo-perk-3',
        period: thisMonth,
        status: 'claimed',
        claimed_date: addDays(today, -5),
        notes: '',
      },
    ],

    grants: [
      {
        id: 'demo-grant-1',
        label: '2024 RSU Grant',
        company: 'Acme Corp',
        broker: 'Fidelity',
        type: 'rsu',
        who: 'chang',
        grant_date: addDays(today, -480),
        total_shares: 400,
        schedule_note: 'Quarterly over 4 years',
        notes: '',
      },
      {
        id: 'demo-grant-2',
        label: '2025 RSU Grant',
        company: 'Acme Corp',
        broker: 'Fidelity',
        type: 'rsu',
        who: 'kiju',
        grant_date: addDays(today, -200),
        total_shares: 200,
        schedule_note: 'Annual over 4 years',
        notes: '',
      },
    ],

    vesting: [
      {
        id: 'demo-vest-1',
        grant_id: 'demo-grant-1',
        type: 'rsu',
        who: 'chang',
        date: addDays(today, -60),
        shares: 25,
        gross_value: 8750,
        status: 'vested',
        sold_amount: null,
        sold_date: null,
        notes: '',
      },
      {
        id: 'demo-vest-2',
        grant_id: 'demo-grant-1',
        type: 'rsu',
        who: 'chang',
        date: addDays(today, 28),
        shares: 25,
        gross_value: 9100,
        status: 'upcoming',
        sold_amount: null,
        sold_date: null,
        notes: '',
      },
      {
        id: 'demo-vest-3',
        grant_id: 'demo-grant-1',
        type: 'rsu',
        who: 'chang',
        date: addDays(today, 118),
        shares: 25,
        gross_value: 9100,
        status: 'upcoming',
        sold_amount: null,
        sold_date: null,
        notes: '',
      },
      {
        id: 'demo-vest-4',
        grant_id: 'demo-grant-2',
        type: 'rsu',
        who: 'kiju',
        date: addDays(today, 43),
        shares: 50,
        gross_value: 12500,
        status: 'upcoming',
        sold_amount: null,
        sold_date: null,
        notes: '',
      },
    ],

    backlog: [
      {
        id: 'demo-task-1',
        title: 'Call insurance about renewal',
        status: 'open',
        priority: 'high',
        due_date: addDays(today, 5),
        done_date: null,
        snoozed_until: null,
        notes: 'Policy renews next month',
      },
      {
        id: 'demo-task-2',
        title: 'Set up automatic rent payment',
        status: 'in_progress',
        priority: 'medium',
        due_date: null,
        done_date: null,
        snoozed_until: null,
        notes: '',
      },
      {
        id: 'demo-task-3',
        title: 'Review Spotify Family plan members',
        status: 'open',
        priority: 'low',
        due_date: null,
        done_date: null,
        snoozed_until: addDays(today, 14),
        notes: '',
      },
      {
        id: 'demo-task-4',
        title: 'File reimbursement for travel credit',
        status: 'done',
        priority: 'high',
        due_date: null,
        done_date: addDays(today, -10),
        snoozed_until: null,
        notes: '',
      },
      {
        id: 'demo-task-5',
        title: 'Compare internet providers',
        status: 'open',
        priority: 'low',
        due_date: null,
        done_date: null,
        snoozed_until: null,
        notes: 'Spectrum contract ends in 3 months',
      },
    ],

    warranties: [
      {
        id: 'demo-warranty-1',
        name: 'MacBook Pro 14"',
        brand: 'Apple',
        who: 'chang',
        category: 'electronics',
        store: 'Apple Store',
        serial: 'C02XJ4ABMD6T',
        purchase_date: addDays(today, -400),
        expiry_date: addDays(today, 330),
        coverage: 'AppleCare+',
        notes: '',
        archived: false,
      },
      {
        id: 'demo-warranty-2',
        name: 'LG OLED TV 65"',
        brand: 'LG',
        who: 'joint',
        category: 'electronics',
        store: 'Best Buy',
        serial: 'LG65C3PSA2024',
        purchase_date: addDays(today, -200),
        expiry_date: addDays(today, 25),
        coverage: '2-year extended',
        notes: '',
        archived: false,
      },
      {
        id: 'demo-warranty-3',
        name: 'Dyson V15 Vacuum',
        brand: 'Dyson',
        who: 'joint',
        category: 'appliance',
        store: 'Dyson.com',
        serial: 'DYS-V15-DEMO',
        purchase_date: addDays(today, -740),
        expiry_date: addDays(today, -5),
        coverage: '2-year manufacturer',
        notes: '',
        archived: false,
      },
      {
        id: 'demo-warranty-4',
        name: 'iPhone 15 Pro',
        brand: 'Apple',
        who: 'kiju',
        category: 'electronics',
        store: 'Apple Store',
        serial: 'F2LX91NDEMO',
        purchase_date: addDays(today, -300),
        expiry_date: addDays(today, 65),
        coverage: 'AppleCare+',
        notes: '',
        archived: false,
      },
    ],
  };
}
